CREATE TABLE recipe(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    ingredient VARCHAR(5000) NOT NULL,
    steps VARCHAR(5000) NOT NULL,
    category VARCHAR(50),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
